<a href="https://colab.research.google.com/github/jmanzer7/TensorFlow-Notebooks/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we're going to cover fundamental concepts of tensors using TensorFlow

More Specifically, we're going to cover:
* Introduction to tensors
* Getting info from tensors 
* Manipulating tensors
* Tensors & NumPy
* Using #tf.function
* Using GPUs with Tensorflow
* Excersises

Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimensions of a tensor (ndim stands for # of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant((10, 10))
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check dimension of the vector
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimesnion)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [10]:
# Create another matrix
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
# specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
# What is the number of dimensions of another_matrix?
another_matrix.ndim

2

In [13]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3], 
                       [4, 5, 6]], 
                       [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
# Number of dimensions for tesnor
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: number with direction
* Maatrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (n can be any number, a 0-dimensional tesnro is a scalar, a 1-dimensional tensor is a scalar)